### ISSUE TITLE
Push notifications from backend

### ISSUE THREAD

**Issue by sri-vathsa** [moshfeu/chrome-extension-notification-demo#1]
What if we want to have a notification listener? i.e., a push notification will be sent from the backend of the application to the chrome extension and then the pop up will be shown..

**Comment by moshfeu** [comment]
Do you mean the the extension will listen to your server (web-socket?), when there is a new message, the extension will show a notification with the message?

**Comment by sri-vathsa** [comment]
I am creating an extension that injects code into google calendar.

background.js
----
```
chrome.webNavigation.onCompleted.addListener(function(details) {

  tabId = details['tabId'];
  alert("This is my favorite website!");
  chrome.tabs.sendMessage(tabs[0].id, {greeting: "hello"}, function(response) {
    console.log("success");
  });
}, {url: [{urlMatches : 'https://calendar.google.com/calendar/r/eventedit'}]});
```
----
content.js
```
chrome.runtime.onMessage.addListener(function(message, callback) {
console.log('received')
  });
```
------
On doing this I get an error 
```
_generated_background_page.html Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

**Comment by moshfeu** [comment]
Not seems like it's connected to the post's subject. Anyway, is this answers your question? https://stackoverflow.com/a/54686484/863110

**Comment by sri-vathsa** [comment]
That works thanks :)

**Comment by moshfeu** [comment]
Glad to hear!
