### ISSUE TITLE
Repositioning or Offsetting Button Location

### ISSUE THREAD

**Issue by MVBoarder** [moshfeu/chrome-extension-notification-demo#4]
Hello Moshfeu,

First off, great demo showing the use of this and works great for me, thank you for this help!

At this point, I'm trying to modify the location of the button but am having trouble relocating it to a particular position on a website.  The document.body.insertAdjacentElement() works well, but seems limited to the body attribute and "afterbegin", "beforeend", etc. in relation to a website's body attribute.

Could you please point me in the right direction as to how I could offset the button location to a different location on a webpage?

Thanks ahead of time for your help and looking forward to hearing back from you!

**Comment by moshfeu** [comment]
Hi, sorry for the (very) late response.
Is this issue still relevant?
